add home work two and fixed CheckStyle
LomovKirill/KirillLomov_LevelUp pull request #1
Opened 2022-10-03 19:58 UTC by LomovKirill

2022-10-10 07:14 UTC, khda91 requested changes
Необходимо исправить замечания

2022-10-10 07:14 UTC, khda91 commented on pom.xml
> +        <dependency>
Судя по всем для запуска используется `Junit`, так что эту зависимость можно удалить

2022-10-10 07:14 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/HappyTicketCalculation.java
> +    public static Object getHappyTicket(String numberTicket) {
А почему метод возвращает `Object`? В задании сказано, что метод может возвращать 2 значения `true`/`false`

2022-10-10 07:14 UTC, khda91 commented on src/test/java/ru/levelp/at/homework2/NegativeDataProvider.java
> +    public static Stream<Arguments> dataTest() {
Не хватает данных для проверки. 
Что произойдёт есть 
1. Строка будет пустая?
2. Строка будет < 6 символов?
3. Строка будет > 6 символов?
4. Строка будет содержать буквы?

2022-10-10 07:14 UTC, khda91 commented on src/test/java/ru/levelp/at/homework2/NegativeTestIT.java
> +        System.out.println("123");
А зачем тут `System.out.println`?

2022-10-10 19:14 UTC, LomovKirill commented on pom.xml
> +        <dependency>
Убрал

2022-10-10 19:14 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework2/HappyTicketCalculation.java
> +    public static Object getHappyTicket(String numberTicket) {
Не внимательный, исправил

2022-10-10 19:14 UTC, LomovKirill commented on src/test/java/ru/levelp/at/homework2/NegativeDataProvider.java
> +    public static Stream<Arguments> dataTest() {
Дополнил

2022-10-10 19:15 UTC, LomovKirill commented on src/test/java/ru/levelp/at/homework2/NegativeTestIT.java
> +        System.out.println("123");
Дебажил сьюты по моему, не убрал перед пушим, убрал

2022-10-11 06:26 UTC, khda91 requested changes
Исправь пожалуйста комментарии

2022-10-11 06:26 UTC, khda91 commented on pom.xml
> +<!--                    <execution>-->
А почему закомментированно? Так не должно быть

2022-10-11 06:26 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/HappyTicketCalculation.java
> +    @SuppressWarnings("checkstyle:LineLength")
Зачем данная аннотация?

2022-10-11 06:26 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/HappyTicketCalculation.java
> +    private static final String regexp = "^[0-9]\\d{5}";
`^[0-9]{6}`?

2022-10-11 07:10 UTC, LomovKirill commented on pom.xml
> +<!--                    <execution>-->
Исправил

2022-10-11 07:10 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework2/HappyTicketCalculation.java
> +    @SuppressWarnings("checkstyle:LineLength")
Удалил, с каким то изменением заехало

2022-10-11 07:10 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework2/HappyTicketCalculation.java
> +    private static final String regexp = "^[0-9]\\d{5}";
Можно и так, можно и "\d{6}", исправил на "^[0-9]{6}"

2022-10-12 06:23 UTC, khda91 approved these changes
Домашняя работа принята

2022-10-12 06:24 UTC, merged