Homework3
LomovKirill/KirillLomov_LevelUp pull request #2
Opened 2022-10-14 18:44 UTC by LomovKirill

2022-10-17 13:17 UTC, khda91 requested changes
Вижу что реализованы PageObjects. Для первой работы по селениуму необходимо сделать тесты без использования PageObjects

2022-10-19 17:13 UTC, khda91 requested changes
1. Убрать все sleep из когда и заменить на ожидания
2. исправить ошибки checkstyle и включитиь его

2022-10-19 17:13 UTC, khda91 commented on src/main/java/ru/levelp/at/homework3/SleepUtils.java
> +public class SleepUtils {
А что здесь делает этот класс? Никаких sleep в тестах быть не может

2022-10-19 17:13 UTC, khda91 commented on pom.xml
> +<!--                    <execution>-->
Раскоментировать и исправить ошибки вызванные checkstyle
![image](https://user-images.githubusercontent.com/7585107/196758777-965f4b3f-6b80-4615-a0b6-8c80b294d50f.png)

2022-10-19 17:13 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/DeleteMailTest.java
> +        SleepUtils.sleep(1500);
Thread.sleep нельзя использовать в коде. Его нужно заменить на явное или неявное ожидание

2022-10-21 19:26 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework3/SleepUtils.java
> +public class SleepUtils {
Исправил

2022-10-21 19:26 UTC, LomovKirill commented on pom.xml
> +<!--                    <execution>-->
Исправил, проверил, ошибок checkstyle нет

2022-10-21 19:27 UTC, LomovKirill commented on src/test/java/ru/levelp/at/homework3/DeleteMailTest.java
> +        SleepUtils.sleep(1500);
Исправил на явное и неявное, использовал вместе по рекомендациям

2022-10-30 19:48 UTC, khda91 approved these changes
Работа принята

2022-10-31 07:13 UTC, merged