add prop and refactoring
LomovKirill/KirillLomov_LevelUp pull request #3
Opened 2022-10-17 15:58 UTC by LomovKirill

2022-10-19 17:51 UTC, khda91 requested changes
Исправить замечания к работе

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/CreateEmail.java
> +public class CreateEmail {
Этот класс - страница, тест, сущность? Из названия не понятно предназначение этого класса.

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/CreateEmail.java
> +
Эти поля можно вынести в базовый класс и унаследоваться от него

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/CreateEmail.java
> +    }
```java
public CreateEmail(WebDriver driver) {
    super(driver);
}
```

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/DeleteEmail.java
> +public class DeleteEmail {
Комментарии аналогично `CreateEmail`

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/GetProperties.java
> +@SuppressWarnings("checkstyle:EmptyLineSeparator")
Удалить. Этой аннотации быть не должно

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/LoginMail.java
> +public class LoginMail {
Комментарии аналогично `CreateEmail`

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/LogoutMail.java
> +public class LogoutMail {
Комментарии аналогично `CreateEmail`

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/OpenFolderEmail.java
> +public class OpenFolderEmail {
Комментарии аналогично `CreateEmail`

2022-10-19 17:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/SleepUtils.java
> +public class SleepUtils {
Необходимо удалить. Sleep быть не должно в тестах, необходимо использовать ожидания

2022-10-19 17:51 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/DeleteMailTest.java
> +        SleepUtils.sleep(5000);
Никаких Thread.sleep в тестах

2022-10-19 17:51 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/SaveDraftMailTest.java
> +        String actualDraft = driver.findElement(By.xpath("//div[@class='layout__main-frame']"
А зачем тут прямое обращение к `driver.findElement`? 
При подходе Page Object в тестх не должно быть никаких обращений к драйверу. Всё общение с драйвером происходит в рамках Page Object, в тесте может быть максимум инициализация драйвера

2022-10-19 17:51 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/SendMailTest.java
> +        String actualSubject = driver.findElement(By.xpath("//div[@class='layout__main-frame']"
Не должно быть прямого обращения к драйверу в тестах

2022-10-21 21:50 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework4/CreateEmail.java
> +public class CreateEmail {
Поменял. Можешь привести примеры пожалуйста, как бы ты назвал, и возможно разделил функциональность как то по другому?

2022-10-21 21:50 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework4/CreateEmail.java
> +
Сделал

2022-10-21 21:51 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework4/CreateEmail.java
> +    }
Да про этот элемент уже к реализации забыл, сделал.

2022-10-21 21:51 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework4/DeleteEmail.java
> +public class DeleteEmail {
Поменял

2022-10-21 21:54 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework4/GetProperties.java
> +@SuppressWarnings("checkstyle:EmptyLineSeparator")
Снова не усмотрел, убрал

2022-10-21 21:54 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework4/OpenFolderEmail.java
> +public class OpenFolderEmail {
Поменял

2022-10-21 21:54 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework4/SleepUtils.java
> +public class SleepUtils {
Убрал

2022-10-21 21:54 UTC, LomovKirill commented on src/test/java/ru/levelp/at/homework4/DeleteMailTest.java
> +        SleepUtils.sleep(5000);
Убрал

2022-10-21 21:55 UTC, LomovKirill commented on src/test/java/ru/levelp/at/homework4/SaveDraftMailTest.java
> +        String actualDraft = driver.findElement(By.xpath("//div[@class='layout__main-frame']"
В тестах больше нет обращения к драйверу

2022-10-21 21:55 UTC, LomovKirill commented on src/test/java/ru/levelp/at/homework4/SendMailTest.java
> +        String actualSubject = driver.findElement(By.xpath("//div[@class='layout__main-frame']"
В тестах больше нет обращения к драйверу

2022-10-30 19:49 UTC, khda91 approved these changes
Работа принята

2022-10-31 16:28 UTC, merged