Homework6
LomovKirill/KirillLomov_LevelUp pull request #4
Opened 2022-10-25 19:35 UTC by LomovKirill

2022-10-30 20:00 UTC, khda91 requested changes
Исправь пожалуйста, комментарии

2022-10-30 20:00 UTC, khda91 commented on src/main/java/ru/levelp/at/homework6/CommentsClient.java
> +    public Response requestGet() {
Лучше не использовать в именах методов слово `request`. С точки зрения **best practice** лучше называть методы как `getComments` `createComment` и т.д.

2022-10-30 20:00 UTC, khda91 commented on src/main/java/ru/levelp/at/homework6/CommentsClient.java
> +            .header(AUTH, TOKEN)
Можно задать header в глобальной настройке RequestSpecification, чтобы не передавать каждый раз их в тестах

2022-10-30 20:00 UTC, khda91 commented on src/main/java/ru/levelp/at/homework6/CommentsClient.java
> +    public Response requestPost(PostAndPutCommentsRequestData requestData) {
Хоть запросы `POST` и `PUT` очень сильно похожи своими телами, лучше как-то разделить их или переименновать данный класс

2022-10-30 20:00 UTC, khda91 commented on src/main/java/ru/levelp/at/homework6/PostsClient.java
> +public class PostsClient {
Комментарии аналогично `src/main/java/ru/levelp/at/homework6/GetProperties.java`

2022-10-30 20:00 UTC, khda91 commented on src/main/java/ru/levelp/at/homework6/UsersClient.java
> +public class UsersClient {
Комментарии аналогично `src/main/java/ru/levelp/at/homework6/GetProperties.java`

2022-10-30 20:00 UTC, khda91 commented on src/main/java/ru/levelp/at/homework6/model/FailResponseData.java
> +    public static class DataData {
Не очень понятное имя класса

2022-10-30 20:00 UTC, khda91 commented on src/main/java/ru/levelp/at/homework6/model/GetAllCommentsResponseData.java
> +    public static class DataData {
Не очень понятное имя класса

2022-10-30 20:00 UTC, khda91 commented on src/main/java/ru/levelp/at/homework6/model/GetCommentsResponseData.java
> +    }
В целом эти классы, можно вынести из классов, чтобы каждый раз их не дублировать

2022-11-17 21:22 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework6/CommentsClient.java
> +    public Response requestGet() {
Исправил наименование

2022-11-17 21:24 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework6/CommentsClient.java
> +            .header(AUTH, TOKEN)
Не вышло, оставил как есть, если есть решение, поделись пожалуйста. При попытке вынести в глоб. настройки, при каждом новом запросе у меня растет кол-во этого хедера в запросе

2022-11-17 21:24 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework6/CommentsClient.java
> +    public Response requestPost(PostAndPutCommentsRequestData requestData) {
Разделил

2022-11-17 21:25 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework6/PostsClient.java
> +public class PostsClient {
Поправил

2022-11-17 21:25 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework6/UsersClient.java
> +public class UsersClient {
Исправил

2022-11-17 21:25 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework6/model/GetAllCommentsResponseData.java
> +    public static class DataData {
Переименовал

2022-11-17 21:25 UTC, LomovKirill commented on src/main/java/ru/levelp/at/homework6/model/GetCommentsResponseData.java
> +    }
Вынес

2022-11-22 18:33 UTC, khda91 approved these changes
принято

2022-11-23 15:18 UTC, merged